---
- name: Command Module Test
  hosts: all
  tasks:
    - name: run date command
      command: date
      register: log1
    - debug:
        var: log1.stdout_lines

    - name: display file contents
      command: cat /etc/host.conf
      register: log2
    - debug:
        var: log2.stdout_lines

    - name: create directory
      command: mkdir /home/testdir
      register: log3
    - debug:
        var: log3.stdout_lines
